<template>
    <div class="component">
        <!-- <button class="btn btn-primary">click</button> -->
        <div class="container">
            <div class="row">
                <div class="col-md-0"></div>
                <div class="col-md-12">
                    <div class="header">
                        <h5>PRIVACY POLICY</h5>
                        <h1>Our Allegiance to Protecting Your Privacy</h1>
                        <h1>LAST UPDATED</h1>
                        <h5>May 25, 2022</h5>
                    </div><br>
                    <br>

                    <div class="body">
                        <p>
                            Check retail (“we,” “our,” or “us”) is committed to protecting your privacy. 
                            This Privacy Policy explains how your personal information is collected, used, 
                            and disclosed by check retail.<br><br>
                        </p>

                        <div class="content">
                            <h5>Contents:</h5>
                            <ol>
                                <li><a href="#scroll-1">Definitions and key terms</a></li>
                                <li><a href="#scroll-2">What Information Do We Collect?</a></li>
                                <li><a href="#scroll-3">How Do We Use The Information We Collect?</a></li>
                                <li><a href="#scroll-4">When does check retail use end user information from third parties?</a></li>
                                <li><a href="#scroll-5">When does check retail use customer information from third parties?</a></li>
                                <li><a href="#scroll-6">Do we share the information we collect with third parties?</a></li>
                                <li><a href="#scroll-7">Where and when is information collected from customers and end users?</a></li>
                                <li><a href="#scroll-8">How Do We Protect Your Information?</a></li>
                                <li><a href="#scroll-9">Could my information be transferred to other countries?</a></li>
                                <li><a href="#scroll-10">Is the information collected through the check retail Service secure?</a></li>
                                <li><a href="#scroll-11">Personnel</a></li>
                                <li><a href="#scroll-12">Affiliates</a></li>
                                <li><a href="#scroll-13">Governing Law</a></li>
                                <li><a href="#scroll-14">Your Consent</a></li>
                                <li><a href="#scroll-15">Payment Details</a></li>
                                <li><a href="#scroll-16">Kids' Privacy</a></li>
                                <li><a href="#scroll-17">Changes To Our Privacy Policy</a></li>
                                <li><a href="#scroll-18">Third-Party Services</a></li>
                                <li><a href="#scroll-19">Tracking Technologies</a></li>
                                <li><a href="#scroll-20">What is personal data?</a></li>
                                <li><a href="#scroll-21">The Data Protection Principles include requirements such as:</a></li>
                                <li><a href="#scroll-22">Contact Us</a></li>
                            </ol>
                        </div>

                        <p>
                            

                            This Privacy Policy applies to our website, and its associated subdomains (collectively, 
                            our “Service”) alongside our application, check retail. By accessing or using our Service, 
                            you signify that you have read, understood, and agree to our collection, storage, 
                            use, and disclosure of your personal information as described in this Privacy Policy and 
                            our Terms of Service.

                        </p><br>
                        
                        <section id="scroll-1">
                            <p @click="show1 = !show1"><b>Definitions and key terms <img src="../assets/arrow.png" class="arrow" :class="show1 ? 'rotate' : 'rotateBack'" > </b></p><br>

                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show1">
                                    To help explain things as clearly as possible in this Privacy Policy, 
                                    every time any of these terms are referenced, are strictly defined as:<br><br>

                                    <b class="subHeading">Cookie:</b> Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br><br>
                                    <b class="subHeading">Company:</b> When this policy mentions “Company,” “we,” “us,” or “our,” it refers to paddle technologies, (14, ORANGE GATE, PLAMER STREET, OLUYOLE ESTATE IBADAN, IBADAN, OYO STATE, NIGERIA) that is responsible for your information under this Privacy Policy. <br><br>
                                    <b class="subHeading">Customer:</b> Refers to the company, organization or person that signs up to use the check retail Service to manage the relationships with your consumers or service users.<br><br>
                                    <b class="subHeading">Device:</b> Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit check retail and use the services.<br><br>
                                    <b class="subHeading">Personnel:</b> Refers to those individuals who are employed by check retail or are under contract to perform a service on behalf of one of the parties.<br><br>
                                    <b class="subHeading">Personal Data:</b> Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.<br><br>
                                    <b class="subHeading">Service:</b> Refers to the service provided by check retail as described in the relative terms (if available) and on this platform.<br><br>
                                    <b class="subHeading">Third-party service:</b> Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.<br><br>
                                    <b class="subHeading">Website/APP:</b> Check retail."’s" site, which can be accessed via this URL: <br><br>
                                    <b class="subHeading">You</b> : A person or entity that is registered with check retail to use the Services.<br><br>
                                </p>
                            </transition>   
                        
                        </section>

                        <section id="scroll-2">
                            <p @click="show2 = !show2"><b>What Information Do We Collect?  <img src="../assets/arrow.png" class="arrow" :class="show2 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show2">
                                We collect information from you when you visit our app, register on our site, place an order, 
                                subscribe to our newsletter, respond to a survey or fill out a form.<br><br>

                                ° Name / Username<br>
                                ° Phone Numbers<br>
                                ° Email Addresses<br>
                                ° Mailing Addresses<br>
                                ° Password<br>
                                ° Gender<br><br>

                                We also collect information from mobile devices 
                                for a better user experience, although these features are completely optional:<br><br>

                                -Photo Gallery (Pictures): Granting photo gallery access allows the user to upload any picture 
                                from their photo gallery, you can safely deny photo gallery access for this app.

                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-3">
                            <p @click="show3 = !show3" ><b>How Do We Use The Information We Collect?  <img src="../assets/arrow.png" class="arrow" :class="show3 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show3">
                                Any of the information we collect from you may be used in one of the following ways:<br><br>

                                ° To personalize your experience (your information helps us to better respond to your individual needs)<br>
                                ° To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)<br>
                                ° To improvee customer service (your information helps us to more effectively respond to your customer service requests and support needs)<br>
                                ° To process transactions<br>
                                ° Enabling you to participate in promotions, competitions and surveys.<br>
                                ° Complying with our legal obligations, including verifying your identity where necessary.<br>
                                ° Detecting fraud.<br>
                                ° To administer a contest, promotion, survey or other site feature<br>
                                ° To send periodic emails<br>
                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-4">
                            <p @click="show4 = !show4"><b>When does check retail use end user information from third parties?  <img src="../assets/arrow.png" class="arrow" :class="show4 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show4" >
                                Check retail will collect End User Data necessary to provide the check retail services to our customers.<br><br>

                                End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, 
                                we may collect publicly available information from the social media websites you have indicated. 
                                You can control how much of your information social media websites make public by visiting these websites and 
                                changing your privacy settings.
                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-5">
                            <p @click="show5 = !show5"><b>When does check retail use customer information from third parties?  <img src="../assets/arrow.png" class="arrow" :class="show5 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show5">
                                We receive some information from the third parties when you contact us. 
                                For example, when you submit your email address to us to show interest in becoming a check retail customer, 
                                we receive information from a third party that provides automated fraud detection services to check retail. 
                                We also occasionally collect information that is made publicly available on social media websites. 
                                You can control how much of your information social media websites make public by visiting these 
                                websites and changing your privacy settings.
                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-6">
                            <p @click="show6 = !show6"><b>Do we share the information we collect with third parties?  <img src="../assets/arrow.png" class="arrow" :class="show6 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show6">
                                We may share the information that we collect, both personal and non-personal, 
                                with third parties such as advertisers, contest sponsors, promotional and marketing partners, 
                                and others who provide our content or whose products or services we think may interest you. 
                                We may also share it with our current and future affiliated companies and business partners, 
                                and if we are involved in a merger, asset sale or other business reorganization, we may also share 
                                or transfer your personal and non-personal information to our successors-in-interest.<br><br>

                                We may engage trusted third party service providers to perform functions and provide services to us,
                                such as hosting and maintaining our servers and the app, database storage and management, 
                                e-mail management, storage marketing, credit card processing, customer service and fulfilling 
                                orders for products and services you may purchase through the app. We will likely share your personal 
                                information, and possibly some non-personal information, with these third parties to enable them to perform 
                                these services for us and for you.<br><br>

                                We may share portions of our log file data, including IP addresses, for analytics purposes with third 
                                parties such as web analytics partners, application developers, and ad networks. If your IP address 
                                is shared, it may be used to estimate general location and other technographics such as connection speed, 
                                whether you have visited the app in a shared location, and type of the device used to visit the app. 
                                They may aggregate information about our advertising and what you see on the app and then provide auditing, 
                                research and reporting for us and our advertisers.<br><br>

                                We may also disclose personal and non-personal information about you to government or law enforcement 
                                officials or private parties as we, in our sole discretion, believe necessary or appropriate in order 
                                to respond to claims, legal process (including subpoenas), to protect our rights and interests or those 
                                of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or 
                                legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations. <br><br>
                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-7">
                            <p @click="show7 = !show7"><b>Where and when is information collected from customers and end users?    <img src="../assets/arrow.png" class="arrow" :class="show7 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show7">
                                Check retail will collect personal information that you submit to us. We may also receive 
                                personal information about you from third parties as described above.<br><br>
                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-8">
                            <p @click="show8 = !show8"><b>How Do We Protect Your Information?   <img src="../assets/arrow.png" class="arrow" :class="show8 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show8">
                                We implement a variety of security measures to maintain the safety of your personal information 
                                when you place an order or enter, submit, or access your personal information. We offer the use 
                                of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket 
                                Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be 
                                accessible by those authorized with special access rights to such systems, and are required to keep 
                                the information confidential. After a transaction, your private information (credit cards, social 
                                security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the 
                                absolute security of any information you transmit to check retail or guarantee that your information 
                                on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, 
                                technical, or managerial safeguards.
                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-9">
                            <p @click="show9 = !show9"><b>Could my information be transferred to other countries?  <img src="../assets/arrow.png" class="arrow" :class="show9 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show9">
                                check retail is incorporated in Nigeria. Information collected via our website, through direct interactions 
                                with you, or from use of our help services may be transferred from time to time to our offices or personnel, 
                                or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including 
                                countries that may not have laws of general applicability regulating the use and transfer of such data. 
                                To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the 
                                trans-border transfer and hosting of such information.
                                </p>
                            </transition>
                            
                        </section>

                        <section id="scroll-10">
                            <p @click="show10 = !show10"><b>Is the information collected through the check retail Service secure?   <img src="../assets/arrow.png" class="arrow" :class="show10 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <transition name="dropDown" mode="out-in" appear >
                                <p v-show="show10">
                                We take precautions to protect the security of your information. We have physical, 
                                electronic, and managerial procedures to help safeguard, prevent unauthorized access, 
                                maintain data security, and correctly use your information. However, neither people nor security 
                                systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, 
                                make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your 
                                personal information, we cannot guarantee its absolute security. If applicable law imposes any 
                                non-disclaimable duty to protect your personal information, you agree that intentional misconduct 
                                will be the standards used to measure our compliance with that duty.
                                </p>
                            </transition>
                            
                        </section>

                        <p id="scroll-11">
                            <b class="subHeading">Personnel</b><br><br>
                            If you are a check retail worker or applicant, we collect information you voluntarily provide to us. 
                            We use the information collected for Human Resources purposes in order to administer benefits to workers and 
                            screen applicants.<br><br>

                            You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to 
                            communications and other information you receive from us, or (3) receive a record of the information we have 
                            relating to you. Such updates, corrections, changes and deletions will have no effect on other information that 
                            we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior 
                            to such update, correction, change or deletion.
                        </p><br><br>

                        <p id="scroll-12">
                            <b class="subHeading">Affiliates</b><br><br>
                            We may disclose information (including personal information) about you to our Corporate Affiliates. 
                            For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or 
                            indirectly controls, is controlled by or is under common control with check retail, whether by ownership 
                            or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated 
                            by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
                        </p><br><br>

                        <p id="scroll-13">
                            <b class="subHeading">Governing Law</b><br><br>
                            This Privacy Policy is governed by the laws of Nigeria without regard to its conflict of laws provision. 
                            You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising 
                            between the parties under or in connection with this Privacy Policy except for those individuals who may have 
                            rights to make claims under Privacy Shield, or the Swiss-US framework.<br><br>

                            The laws of Nigeria, excluding its conflicts of law rules, shall govern this Agreement and your use of the app. 
                            Your use of the app may also be subject to other local, state, national, or international laws.<br><br>

                            By using check retail or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not 
                            agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the 
                            website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not 
                            significantly affect the use or disclosure of your personal information will mean that you accept those changes.
                        </p><br><br>

                        <p id="scroll-14">
                            <b class="subHeading">Your Consent</b><br><br>
                            We've updated our Privacy Policy to provide you with complete transparency into what is being set 
                            when you visit our site and how it's being used. By using our app, registering an account, or 
                            making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
                        </p><br><br>

                        <p id="scroll-15">
                            <b class="subHeading">Payment Details</b><br><br>
                            In respect to any credit card or other payment processing details you have provided us, 
                            we commit that this confidential information will be stored in the most secure manner possible.
                        </p><br><br>

                        <p id="scroll-16">
                            <b class="subHeading">Kids' Privacy</b><br><br>
                            We collect information from kids under the age of 13 just to better our services. 
                            If You are a parent or guardian and You are aware that Your child has provided Us 
                            with Personal Data without your permission, please contact Us. If We become aware that 
                            We have collected Personal Data from anyone under the age of 13 without verification of 
                            parental consent, We take steps to remove that information from Our servers.
                        </p><br><br>

                        <p id="scroll-17">
                            <b class="subHeading">Changes To Our Privacy Policy</b><br><br>
                            We may change our Service and policies, and we may need to make changes to this Privacy 
                            Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, 
                            we will notify you (for example, through our Service) before we make changes to this Privacy 
                            Policy and give you an opportunity to review them before they go into effect. Then, if you 
                            continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want 
                            to agree to this or any updated Privacy Policy, you can delete your account.
                        </p><br><br>

                        <p id="scroll-18">
                            <b class="subHeading">Third-Party Services</b><br><br>
                            We may display, include or make available third-party content (including data, information, 
                            applications and other products services) or provide links to third-party websites or services 
                            ("Third- Party Services"). You acknowledge and agree that check retail shall not be responsible 
                            for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright 
                            compliance, legality, decency, quality or any other aspect thereof. check retail does not assume 
                            and shall not have any liability or responsibility to you or any other person or entity for any 
                            Third-Party Services.<br><br>

                            Third-Party Services and links thereto are provided solely as a convenience to you and you 
                            access and use them entirely at your own risk and subject to such third parties' terms and conditions.
                        </p><br><br>

                        <p id="scroll-19">
                            <b class="subHeading">Tracking Technologies</b><br><br>
                            ° Google Maps API:<br><br>

                            Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, 
                            display live data synching with location, plan routes, or create a mashup just to name a few.
                            Google Maps API may collect information from You and from Your Device for security purposes.
                            Google Maps API collects information that is held in accordance with its Privacy Policy
                        </p><br><br>

                        <p id="scroll-20">
                            <b class="subHeading">What is personal data?</b><br><br>
                            Any data that relates to an identifiable or identified individual. GDPR covers a broad 
                            spectrum of information that could be used on its own, or in combination with other pieces of 
                            information, to identify a person. Personal data extends beyond a person’s name or email address. 
                            Some examples include financial information, political opinions, genetic data, biometric data, 
                            IP addresses, physical address, sexual orientation, and ethnicity.
                        </p><br><br>

                        <p id="scroll-21">
                            <b class="subHeading">The Data Protection Principles include requirements such as:</b><br><br>
                                ° Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.<br>
                                ° Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.<br>
                                ° Personal data should be held no longer than necessary to fulfil its purpose.<br>
                                ° People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.<br>
                        </p><br><br>

                        <p id="scroll-22">
                            <b class="subHeading">Contact Us</b>
                            Don't hesitate to contact us if you have any questions.<br><br>

                            ° Via Email:  <b>hello.paddle@gmail.com</b><br><br>
                            ° Via Phone Number:  <b>08149734622</b>
                        </p><br><br>



                    </div>
                </div>
                <div class="col-md-0"></div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
  name: 'policy',
  data() {
    return {
        show1: false,
        show2: false,
        show3: false,
        show4: false,
        show5: false,
        show6: false,
        show7: false,
        show8: false,
        show9: false,
        show10: false
    }
  }
  
}
</script>

<style scoped>

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Poppins:wght@300;500;600&display=swap');

.header {
    color: red;
}
/* .header h5 {
    font-weight: lighter;
} */
.header h1 {
    font-weight: bolder;
}
.header h1:nth-child(2) {
    border-bottom: 2px solid red;
    border-top: 2px solid red;
    padding-bottom: 10px;
    padding-top: 10px;
}
.header h1:nth-child(3) {
    font-weight: bolder;
    color: black;
    margin-top: 100px;
}
.content {
    text-align: left;
    padding: 40px;
    background-color: rgb(241, 241, 241);
    border: 1px solid rgb(228, 228, 228);
    margin: 40px 0px 40px 0px;
}
a {
    text-decoration: none;
    color: black;
}
a:hover {
    color: brown;
}
.subHeading {
    color: rgb(199, 6, 6);
}
.body p {
    font-size: 16px;
    /* font-weight: lighter; */
    text-align: left;
}
.body p b {
    font-weight: 700;
    font-family: poppins;
}
.col-md-12 {
    text-align: center;
    padding: 40px;
}
.arrow {
    height: 16px;
    width: 16px;
    float: right;
    margin-right: 3px;
}
.rotate {
    transform: rotate(90deg);
    transition: all 0.4s ease;
}
.rotateBack {
    transform: rotate(0deg);
    transition: all 0.4s ease;
}

.dropDown-enter-from {
  opacity: 0;
  transform: scale(0) translateX(500px);
}
.dropDown-enter-to {
  opacity: 1;
  transform: scale(1) translateX(0);
}
.dropDown-enter-active {
  transition: all 0.4s ease;
}

.dropDown-leave-from {
  opacity: 1;
  transform: scale(1) translateY(0);
}
.dropDown-leave-to {
  opacity: 0;
  transform: scale(0) translateY(-500px);
}
.dropDown-leave-active {
  transition: all 0.4s ease;
  /* position: absolute; */
}
.dropDown-move {
  transition: all 0.9s ease;
}
.component {
    animation-name: fade-in;
    animation-duration: 0.8s;
    color: black;
}
/* 
section p:nth-child(1){
    position: relative;
} */
section p:nth-child(1):hover {
    transform: scale(1.02);
}
@keyframes fade-in {
    from{opacity: 0;}
    to {opacity: 1;}
}

@media screen and (max-width: 700px){
    * {
        margin: 0%;
        padding: 0%;   
    }
    .component {
        display: flex;
        overflow-x: hidden;
    }
    .col-md-12{
        overflow-x: hidden;
        padding: 22px;
    }
    .header{
        text-align: center;
    }
    .header h1 {
        /* width: 250px; */
        font-size: 30px;
        margin-top: 10px;
        padding: 20px;

    }
    .header h5 {
        /* width: 250px; */
        font-size: 20px;

    }
    .body p {
        font-size: 14px;
        /* font-weight: 4; */
        text-align: left;
        /* width: 280px; */
    }
    section p:nth-child(1){
        max-width: 390px;
        
    }
    img{
        transform: translateY(20px);
    }
}

</style>