<template>
    <div class="component">
        <!-- <button class="btn btn-primary">click</button> -->
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="header">
                        <h5>PRIVACY POLICY</h5>
                        <h1>Our Commitment to Protecting Your Privacy</h1>
                        <h1>UPDATED AT</h1>
                        <h5>May 25, 2022</h5>
                    </div><br>
                    <br>

                    <div class="body">
                        <p>
                            Check retail (“we,” “our,” or “us”) is committed to protecting your privacy. 
                            This Privacy Policy explains how your personal information is collected, used, 
                            and disclosed by check retail.<br><br>

                            This Privacy Policy applies to our website, and its associated subdomains (collectively, 
                            our “Service”) alongside our application, check retail. By accessing or using our Service, 
                            you signify that you have read, understood, and agree to our collection, storage, 
                            use, and disclosure of your personal information as described in this Privacy Policy and 
                            our Terms of Service.

                        </p><br>

                        <section>
                            <p @click="show1 = !show1"><b>Definitions and key terms <img src="../assets/arrow.png" class="arrow" :class="show1 ? 'rotate' : 'rotateBack'" > </b></p><br>

                        <p v-show="show1">
                            To help explain things as clearly as possible in this Privacy Policy, 
                            every time any of these terms are referenced, are strictly defined as:<br><br>

                            <b>-Cookie:</b> Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br><br>
                            <b>-Company:</b> When this policy mentions “Company,” “we,” “us,” or “our,” it refers to paddle technologies, (14, ORANGE GATE, PLAMER STREET, OLUYOLE ESTATE IBADAN, IBADAN, OYO STATE, NIGERIA) that is responsible for your information under this Privacy Policy. <br><br>
                            <b>-Customer:</b> Refers to the company, organization or person that signs up to use the check retail Service to manage the relationships with your consumers or service users.<br><br>
                            <b>-Device:</b> Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit check retail and use the services.<br><br>
                            <b>-Personnel:</b> Refers to those individuals who are employed by check retail or are under contract to perform a service on behalf of one of the parties.<br><br>
                            <b>-Personal Data:</b> Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.<br><br>
                            <b>-Service:</b> Refers to the service provided by check retail as described in the relative terms (if available) and on this platform.<br><br>
                            <b>-Third-party service:</b> Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.<br><br>
                            <b>-Website/APP:</b> Check retail."’s" site, which can be accessed via this URL: <br><br>
                            <b>-You</b> : A person or entity that is registered with check retail to use the Services.<br><br>
  

                        </p>
                        </section>

                        <section>
                            <p @click="show2 = !show2"><b>What Information Do We Collect?  <img src="../assets/arrow.png" class="arrow" :class="show2 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <p v-show="show2">
                                We collect information from you when you visit our app, register on our site, place an order, 
                                subscribe to our newsletter, respond to a survey or fill out a form.<br><br>

                                -Name / Username<br>
                                -Phone Numbers<br>
                                -Email Addresses<br>
                                -Mailing Addresses<br>
                                -Password<br>
                                - Gender<br><br>

                                We also collect information from mobile devices 
                                for a better user experience, although these features are completely optional:<br><br>

                                -Photo Gallery (Pictures): Granting photo gallery access allows the user to upload any picture 
                                from their photo gallery, you can safely deny photo gallery access for this app.

                            </p>
                        </section>

                        <section>
                            <p @click="show3 = !show3" ><b>How Do We Use The Information We Collect?  <img src="../assets/arrow.png" class="arrow" :class="show3 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <p v-show="show3">
                                Any of the information we collect from you may be used in one of the following ways:<br><br>

                                -To personalize your experience (your information helps us to better respond to your individual needs)<br>
                                -To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)<br>
                                -To improvee customer service (your information helps us to more effectively respond to your customer service requests and support needs)<br>
                                -To process transactions<br>
                                - Enabling you to participate in promotions, competitions and surveys.<br>
                                - Complying with our legal obligations, including verifying your identity where necessary.<br>
                                - Detecting fraud.<br>
                                -To administer a contest, promotion, survey or other site feature<br>
                                -To send periodic emails<br>

                            </p>
                        </section>

                        <section>
                            <p @click="show4 = !show4"><b>When does check retail use end user information from third parties?  <img src="../assets/arrow.png" class="arrow" :class="show4 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <p v-show="show4" >
                                Check retail will collect End User Data necessary to provide the check retail services to our customers.<br><br>

                                End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, 
                                we may collect publicly available information from the social media websites you have indicated. 
                                You can control how much of your information social media websites make public by visiting these websites and 
                                changing your privacy settings.
                            </p>
                        </section>

                        <section>
                            <p @click="show5 = !show5"><b>When does check retail use customer information from third parties?  <img src="../assets/arrow.png" class="arrow" :class="show5 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <p v-show="show5">
                                We receive some information from the third parties when you contact us. 
                                For example, when you submit your email address to us to show interest in becoming a check retail customer, 
                                we receive information from a third party that provides automated fraud detection services to check retail. 
                                We also occasionally collect information that is made publicly available on social media websites. 
                                You can control how much of your information social media websites make public by visiting these 
                                websites and changing your privacy settings.
                            </p>
                        </section>

                        <section>
                            <p @click="show6 = !show6"><b>Do we share the information we collect with third parties?  <img src="../assets/arrow.png" class="arrow" :class="show6 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <p v-show="show6">
                                We may share the information that we collect, both personal and non-personal, 
                                with third parties such as advertisers, contest sponsors, promotional and marketing partners, 
                                and others who provide our content or whose products or services we think may interest you. 
                                We may also share it with our current and future affiliated companies and business partners, 
                                and if we are involved in a merger, asset sale or other business reorganization, we may also share 
                                or transfer your personal and non-personal information to our successors-in-interest.<br><br>

                                We may engage trusted third party service providers to perform functions and provide services to us,
                                such as hosting and maintaining our servers and the app, database storage and management, 
                                e-mail management, storage marketing, credit card processing, customer service and fulfilling 
                                orders for products and services you may purchase through the app. We will likely share your personal 
                                information, and possibly some non-personal information, with these third parties to enable them to perform 
                                these services for us and for you.<br><br>

                                We may share portions of our log file data, including IP addresses, for analytics purposes with third 
                                parties such as web analytics partners, application developers, and ad networks. If your IP address 
                                is shared, it may be used to estimate general location and other technographics such as connection speed, 
                                whether you have visited the app in a shared location, and type of the device used to visit the app. 
                                They may aggregate information about our advertising and what you see on the app and then provide auditing, 
                                research and reporting for us and our advertisers.<br><br>

                                We may also disclose personal and non-personal information about you to government or law enforcement 
                                officials or private parties as we, in our sole discretion, believe necessary or appropriate in order 
                                to respond to claims, legal process (including subpoenas), to protect our rights and interests or those 
                                of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or 
                                legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations. <br><br>
                            </p>
                        </section>

                        <section>
                            <p @click="show7 = !show7"><b>Where and when is information collected from customers and end users?    <img src="../assets/arrow.png" class="arrow" :class="show7 ? 'rotate' : 'rotateBack'" ></b></p><br>
                            <p v-show="show7">
                                Check retail will collect personal information that you submit to us. We may also receive 
                                personal information about you from third parties as described above.<br><br>
                            </p>
                        </section>




                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
  name: 'policy',
  data() {
    return {
        show1: false,
        show2: false,
        show3: false,
        show4: false,
        show5: false,
        show6: false,
        show7: false,
        show8: false
    }
  }
  
}
</script>

<style scoped>
.header {
    color: red;
}
.header h5 {
    font-weight: lighter;
}
.header h1 {
    font-weight: bolder;
}
.header h1:nth-child(3) {
    font-weight: bolder;
    color: black;
    margin-top: 150px;
}
.body p {
    font-size: 18px;
    /* font-weight: lighter; */
    text-align: left;
}
.body p b {
    font-weight: 700;
}
.col-md-8 {
    text-align: center;
    padding: 40px;
}
.arrow {
    height: 20px;
    width: 20px;
    float: right;
    margin-right: 5px;
}
.rotate {
    transform: rotate(90deg);
    transition: all 0.4s ease;
}
.rotateBack {
    transform: rotate(0deg);
    transition: all 0.4s ease;
}

@media screen and (max-width: 700px){
    * {
        margin: 0%;
        padding: 0%;   
    }
    .component {
        display: flex;
        overflow-x: hidden;
    }
    .col-md-8{
        overflow-x: hidden;
        padding: 18px;
    }
    .header{
        text-align: center;
    }
    .header h1 {
        /* width: 250px; */
        font-size: 30px;
        margin-top: 10px;
        padding: 20px;

    }
    .header h5 {
        /* width: 250px; */
        font-size: 20px;

    }
    .body p {
        font-size: 18px;
        /* font-weight: 4; */
        text-align: left;
        /* width: 280px; */
    }
}

</style>